name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up environment
      run: |
        chmod +x setup.sh
        ./setup.sh

    - name: Run application
      run: |
        sbcl --no-sysinit --no-userinit --load Preamble.lisp --eval '(quit)'