name: Common Lisp CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Setup Common Lisp
        uses: 40ants/setup-lisp@v1
        with:
          lisp: sbcl-bin

      - name: Install Dependencies and Run Tests
        run: |
          sbcl --no-sysinit --no-userinit --load Preamble.lisp --eval '(progn (load "MacroTests.lisp") (load "IdentityCheck1_5.lisp") (quit))'
